// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231218033904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Item", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SkuAlias")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vendor")
                        .HasColumnType("text");

                    b.HasKey("Sku");

                    b.ToTable("Items");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Bearing", b =>
                {
                    b.HasBaseType("Domain.Item");

                    b.Property<string>("BoreType")
                        .HasColumnType("text");

                    b.Property<bool>("Flange")
                        .HasColumnType("boolean");

                    b.Property<double>("InnerDiameter")
                        .HasColumnType("double precision");

                    b.Property<bool>("Metric")
                        .HasColumnType("boolean");

                    b.Property<double>("OuterDiameter")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.ToTable("Bearings");
                });

            modelBuilder.Entity("Domain.CustomItem", b =>
                {
                    b.HasBaseType("Domain.Item");

                    b.Property<bool>("Custom")
                        .HasColumnType("boolean");

                    b.ToTable("CustomItems");
                });

            modelBuilder.Entity("Domain.Bearing", b =>
                {
                    b.HasOne("Domain.Item", null)
                        .WithOne()
                        .HasForeignKey("Domain.Bearing", "Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.CustomItem", b =>
                {
                    b.HasOne("Domain.Item", null)
                        .WithOne()
                        .HasForeignKey("Domain.CustomItem", "Sku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
